version: '3'

services:
  web:
    build: .
    ports:
      - "8086:5000"
    depends_on:
      - db

  db:
    image: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data


volumes:
  pg_db:

